### ISSUE TITLE
Always says there are 800 packages updated

### ISSUE THREAD

**Issue by Xylemon** [dslackw/sun#3]
I may be misunderstanding this program, but isn't it suppose to display a notification when the packages you have installed are updated on the repos?

**Comment by dslackw** [comment]
SUN compared slackpkg ChangeLog with the official Slackware mirror "http://www.slackware.com/changelog/" if not use slackpkg to upgrade distribution then view many packages need upgrade or just run only slackpkg update to update slackpkg local ChangeLog file.

**Comment by Xylemon** [comment]
I use slpkg, so I was hoping this would be nice way to tell me when I have updated packages.

**Comment by dslackw** [comment]
slpkg synchronize with slackpkg ChangeLog file via configuration file default is on. Rules should not have problems. Try out to change mirror in /etc/sun/mirrors
