### ISSUE TITLE
RFC only - xdg autostart 

### ISSUE THREAD

**Issue by rworkman** [dslackw/sun#6]
The /etc/rc.d/rc.sun script seems to be a bit overkill, but I'm not sure exactly how to improve it, hence this issue...
Given that all of the SUN components are expected to run inside a normal user session (that is a correct assumption, right?), it seems that maybe one or two xdg autostart files would handle this better. In short, one could run only the daemon portion (with the expectation that a user will manually check with the sun script from time to time) and one could run what is currently sun_gtk, which starts both the daemon and the gtk tray applet. 
Just my personal opinion here, but I think it's reasonable to expect that anyone wanting to run the daemon portion will also want the gtk tray icon, so make the sun_gtk start the daemon if there's not already an instance running in the user session. 
For anyone not wanting the tray icon, perhaps a sun_cli (or just sun) to work something like this: if a daemon is running in the user session, query it for updates, but if a daemon is not running in the user session, then do whatever it does to query for updates and return that information in the terminal. 
At this point, I'm more asking for your thoughts on the above as opposed to you *doing* the above, although if you think it's a good idea and want to do it, that's fine too - it's just that I'm not opposed to doing the work as long as you approve of it :-)

**Comment by dslackw** [comment]
Hi @rworkman 
Thank you for your contribution to this project here, If I understand correctly, you believe that SUN can operate without rc.sub file. It seems that your thoughts they have a stud. I will do some testing and get back here.

**Comment by dslackw** [comment]
I observe that it is seems difficult (so such designed the SUN) be able to finish and re-start the daemon without rc.sun file, perhaps it will take major changes to the code in the end may not bear the expected result (I note that the demon SUN is a loop that aims to read the "/etc/sun/sun.conf file" and sends the information on gtk icon).
