### ISSUE TITLE
Installing "SUN" on Slackware 14.2 KDE 64 Bit

### ISSUE THREAD

**Issue by Sybelius** [dslackw/sun#7]
Just wishing to inform that "SUN" package which I have been downloading at beginning of July 2016 from:
https://github.com/dslackw/sun
refuses installation with this process:
tar xvf sun-1.2.1.tar.gz
cd sun-1.2.1
./install.sh
(I did as "root")
Got it installed by SlackBuild
Regards

**Comment by dslackw** [comment]
You could make a paste process?

**Comment by Sybelius** [comment]
Hi! - I did the following steps:
1 - Remove "SUN" installed by SlackBuild
2 - Close/open session
3 - Downloaded "sun-master-zip"
4 - Unzip
5 - bash-4.3$ su
Password: 
bash-4.3# cd /home/dominum/sun-master
bash-4.3# ./install.sh
Cannot install /tmp/sun-1.2.1-*_dsw.t?z:  file not found
bash-4.3# 
I have been reinstalling the "SBo" package

**Comment by dslackw** [comment]
You need to download a ready release from here [https://github.com/dslackw/sun/releases](url)

**Comment by Sybelius** [comment]
Thank you! - Already I have been reinstalling "SUN" by SlackBuild before reading your kind answer, it works fine
